### ISSUE TITLE
overlay always there

### ISSUE THREAD

**Issue by ZEYAX** [blakewilson/vidbg#10]
overlay: false, is not working

**Comment by blakewilson** [comment]
I just tested and the overlay is working as expected for me. Please keep in mind that the actual overlay element (`.vidbg-overlay`) will be rendered regardless to be used as a "shield." This prevents showing video related options on right click.

**Comment by ZEYAX** [comment]
> I just tested and the overlay is working as expected for me. Please keep in mind that the actual overlay element (`.vidbg-overlay`) will be rendered regardless to be used as a "shield." This prevents showing video related options on right click.

div “vidbg-overlay”  is always in there,even if I set ”overlay:false“ , I don't think it should be generated
