### ISSUE TITLE
Please add back background positioning like we had in version 1.11

### ISSUE THREAD

**Issue by BackuPs** [blakewilson/vidbg#13]
Can you please add back in the background positioning we had before?  I dont want my video always centered.

Thank you !

**Comment by blakewilson** [comment]
Hey @BackuPs,

I realize this is an old issue, but I don't currently have any plans on supporting the background position like in earlier versions.

The new resize/positioning logic I've implemented makes it more of a challenge to position the video other than the center. I hope you understand.

I will be sure to let you know though if this changes or gets added in the future.

Best,
Blake
