### ISSUE TITLE
Overlay Doesn't Work on Safari

### ISSUE THREAD

**Issue by sfraise** [blakewilson/vidbg#3]
We discovered that the overlay doesn't work on Safari.

On line 338 you're setting the z-index to -1, I removed this as it seems you don't really need it and it solved the issue. I've tested on the latest versions of Chrome, Firefox, Edge and Safari and it seems to work fine.

I also replaced the eval encoded image with a plain rgba semi transparent background color because the project we're working on calls for that but also because eval is evil and I usually set maldetect to nab those things since they're usually used in malware. Would it maybe make more sense to just package that image up with the plugin instead of doing it this way? Another issue with that method is this app we're building needs to be able to be ran locally and not as a traditional website all the time so all of the assets have to be packaged up locally, seems to me like it's just one more external call that doesn't need to be.

**Comment by blakewilson** [comment]
Hi sfraise,

Thank you for your recommendation. These changes will be added within the next release as I agree, plain rgba is better. There will be a setting to adjust the alpha as well.

Have a great day!
