### ISSUE TITLE
Video width is too small after window width increases

### ISSUE THREAD

**Issue by rocketinventor** [blakewilson/vidbg#7]
i.e. If I open a window with a full-width (and nearly full-height) video background and maximize it on a widescreen monitor, the video will not resize to fit full width, instead, the original background image shows through on the left and right side.
I'm not sure if this is the same or the opposite problem as #1.

**Comment by blakewilson** [comment]
Hi @rocketinventor ,

Could you please create a reproducible example? I have not seen this behavior before. The resizing examples I have tested all work as expected.

Best,
Blake
